USE [MContract]
GO

/****** Object:  Table [dbo].[AdsInvitedUsers]    Script Date: 02.05.2020 16:40:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AdsInvitedUsers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AdId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_AdsInvitedUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO